# Generated by Django 5.0.6 on 2024-06-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ManyToManyField(to='jobs.location'),
        ),
    ]
