# Generated by Django 5.0.6 on 2024-06-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
