# Generated by Django 5.0.6 on 2024-07-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Category')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='text_tag_idx',
            old_name='text_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ManyToManyField(to='jobs.category'),
        ),
    ]
