# Generated by Django 5.0.6 on 2024-08-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.CharField(max_length=150, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=200, unique=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=150, unique=True, verbose_name='Tag'),
        ),
    ]
