# Generated by Django 5.0.6 on 2024-08-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_category_text_alter_location_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Apply URL'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('region', 'Region'), ('country', 'Country'), ('city', 'City')], max_length=20, verbose_name='Location Type'),
        ),
    ]
