# Generated by Django 5.0.6 on 2024-08-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
