# Generated by Django 5.0.6 on 2024-09-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
