import { Option } from "@/components/ui/multiple-selector";

export const remoteOptions: Option[] = [
  {
    value: "Remote (Worldwide)",
    label: "Remote (Worldwide)",
    group: "remote",
  },
  {
    value: "Remote (USA)",
    label: "Remote (USA)",
    group: "remote",
  },
];

export const regionOptions: Option[] = [
  { value: "Africa", label: "Africa", group: "region" },
  { value: "Asia", label: "Asia", group: "region" },
  { value: "Europe", label: "Europe", group: "region" },
  { value: "Latin America", label: "Latin America", group: "region" },
  { value: "Middle East", label: "Middle East", group: "region" },
  { value: "North America", label: "North America", group: "region" },
  { value: "Oceania", label: "Oceania", group: "region" },
  { value: "Worldwide", label: "Worldwide", group: "region" },
];

export const countryOptions: Option[] = [
  { value: "Afghanistan", label: "Afghanistan", group: "country" },
  { value: "Albania", label: "Albania", group: "country" },
  { value: "Algeria", label: "Algeria", group: "country" },
  { value: "Andorra", label: "Andorra", group: "country" },
  { value: "Angola", label: "Angola", group: "country" },
  {
    value: "Antigua and Barbuda",
    label: "Antigua and Barbuda",
    group: "country",
  },
  { value: "Argentina", label: "Argentina", group: "country" },
  { value: "Armenia", label: "Armenia", group: "country" },
  { value: "Australia", label: "Australia", group: "country" },
  { value: "Austria", label: "Austria", group: "country" },
  { value: "Azerbaijan", label: "Azerbaijan", group: "country" },
  { value: "Bahamas", label: "Bahamas", group: "country" },
  { value: "Bahrain", label: "Bahrain", group: "country" },
  { value: "Bangladesh", label: "Bangladesh", group: "country" },
  { value: "Barbados", label: "Barbados", group: "country" },
  { value: "Belarus", label: "Belarus", group: "country" },
  { value: "Belgium", label: "Belgium", group: "country" },
  { value: "Belize", label: "Belize", group: "country" },
  { value: "Benin", label: "Benin", group: "country" },
  { value: "Bhutan", label: "Bhutan", group: "country" },
  { value: "Bolivia", label: "Bolivia", group: "country" },
  {
    value: "Bosnia and Herzegovina",
    label: "Bosnia and Herzegovina",
    group: "country",
  },
  { value: "Botswana", label: "Botswana", group: "country" },
  { value: "Brazil", label: "Brazil", group: "country" },
  { value: "Brunei", label: "Brunei", group: "country" },
  { value: "Bulgaria", label: "Bulgaria", group: "country" },
  { value: "Burkina Faso", label: "Burkina Faso", group: "country" },
  { value: "Burundi", label: "Burundi", group: "country" },
  { value: "Cabo Verde", label: "Cabo Verde", group: "country" },
  { value: "Cambodia", label: "Cambodia", group: "country" },
  { value: "Cameroon", label: "Cameroon", group: "country" },
  { value: "Canada", label: "Canada", group: "country" },
  {
    value: "Central African Republic",
    label: "Central African Republic",
    group: "country",
  },
  { value: "Chad", label: "Chad", group: "country" },
  { value: "Chile", label: "Chile", group: "country" },
  { value: "China", label: "China", group: "country" },
  { value: "Colombia", label: "Colombia", group: "country" },
  { value: "Comoros", label: "Comoros", group: "country" },
  { value: "Congo", label: "Congo", group: "country" },
  { value: "Costa Rica", label: "Costa Rica", group: "country" },
  { value: "Croatia", label: "Croatia", group: "country" },
  { value: "Cuba", label: "Cuba", group: "country" },
  { value: "Cyprus", label: "Cyprus", group: "country" },
  { value: "Czech Republic", label: "Czech Republic", group: "country" },
  {
    value: "Democratic Republic of the Congo",
    label: "Democratic Republic of the Congo",
    group: "country",
  },
  { value: "Denmark", label: "Denmark", group: "country" },
  { value: "Djibouti", label: "Djibouti", group: "country" },
  { value: "Dominica", label: "Dominica", group: "country" },
  {
    value: "Dominican Republic",
    label: "Dominican Republic",
    group: "country",
  },
  { value: "East Timor", label: "East Timor", group: "country" },
  { value: "Ecuador", label: "Ecuador", group: "country" },
  { value: "Egypt", label: "Egypt", group: "country" },
  { value: "El Salvador", label: "El Salvador", group: "country" },
  { value: "Equatorial Guinea", label: "Equatorial Guinea", group: "country" },
  { value: "Eritrea", label: "Eritrea", group: "country" },
  { value: "Estonia", label: "Estonia", group: "country" },
  { value: "Eswatini", label: "Eswatini", group: "country" },
  { value: "Ethiopia", label: "Ethiopia", group: "country" },
  { value: "Fiji", label: "Fiji", group: "country" },
  { value: "Finland", label: "Finland", group: "country" },
  { value: "France", label: "France", group: "country" },
  { value: "Gabon", label: "Gabon", group: "country" },
  { value: "Gambia", label: "Gambia", group: "country" },
  { value: "Georgia", label: "Georgia", group: "country" },
  { value: "Germany", label: "Germany", group: "country" },
  { value: "Ghana", label: "Ghana", group: "country" },
  { value: "Greece", label: "Greece", group: "country" },
  { value: "Grenada", label: "Grenada", group: "country" },
  { value: "Guatemala", label: "Guatemala", group: "country" },
  { value: "Guinea", label: "Guinea", group: "country" },
  { value: "Guinea-Bissau", label: "Guinea-Bissau", group: "country" },
  { value: "Guyana", label: "Guyana", group: "country" },
  { value: "Haiti", label: "Haiti", group: "country" },
  { value: "Honduras", label: "Honduras", group: "country" },
  { value: "Hungary", label: "Hungary", group: "country" },
  { value: "Iceland", label: "Iceland", group: "country" },
  { value: "India", label: "India", group: "country" },
  { value: "Indonesia", label: "Indonesia", group: "country" },
  { value: "Iran", label: "Iran", group: "country" },
  { value: "Iraq", label: "Iraq", group: "country" },
  { value: "Ireland", label: "Ireland", group: "country" },
  { value: "Israel", label: "Israel", group: "country" },
  { value: "Italy", label: "Italy", group: "country" },
  { value: "Ivory Coast", label: "Ivory Coast", group: "country" },
  { value: "Jamaica", label: "Jamaica", group: "country" },
  { value: "Japan", label: "Japan", group: "country" },
  { value: "Jordan", label: "Jordan", group: "country" },
  { value: "Kazakhstan", label: "Kazakhstan", group: "country" },
  { value: "Kenya", label: "Kenya", group: "country" },
  { value: "Kiribati", label: "Kiribati", group: "country" },
  { value: "Kosovo", label: "Kosovo", group: "country" },
  { value: "Kuwait", label: "Kuwait", group: "country" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan", group: "country" },
  { value: "Laos", label: "Laos", group: "country" },
  { value: "Latvia", label: "Latvia", group: "country" },
  { value: "Lebanon", label: "Lebanon", group: "country" },
  { value: "Lesotho", label: "Lesotho", group: "country" },
  { value: "Liberia", label: "Liberia", group: "country" },
  { value: "Libya", label: "Libya", group: "country" },
  { value: "Liechtenstein", label: "Liechtenstein", group: "country" },
  { value: "Lithuania", label: "Lithuania", group: "country" },
  { value: "Luxembourg", label: "Luxembourg", group: "country" },
  { value: "Madagascar", label: "Madagascar", group: "country" },
  { value: "Malawi", label: "Malawi", group: "country" },
  { value: "Malaysia", label: "Malaysia", group: "country" },
  { value: "Maldives", label: "Maldives", group: "country" },
  { value: "Mali", label: "Mali", group: "country" },
  { value: "Malta", label: "Malta", group: "country" },
  { value: "Marshall Islands", label: "Marshall Islands", group: "country" },
  { value: "Mauritania", label: "Mauritania", group: "country" },
  { value: "Mauritius", label: "Mauritius", group: "country" },
  { value: "Mexico", label: "Mexico", group: "country" },
  { value: "Micronesia", label: "Micronesia", group: "country" },
  { value: "Moldova", label: "Moldova", group: "country" },
  { value: "Monaco", label: "Monaco", group: "country" },
  { value: "Mongolia", label: "Mongolia", group: "country" },
  { value: "Montenegro", label: "Montenegro", group: "country" },
  { value: "Morocco", label: "Morocco", group: "country" },
  { value: "Mozambique", label: "Mozambique", group: "country" },
  { value: "Myanmar", label: "Myanmar", group: "country" },
  { value: "Namibia", label: "Namibia", group: "country" },
  { value: "Nauru", label: "Nauru", group: "country" },
  { value: "Nepal", label: "Nepal", group: "country" },
  { value: "Netherlands", label: "Netherlands", group: "country" },
  { value: "New Zealand", label: "New Zealand", group: "country" },
  { value: "Nicaragua", label: "Nicaragua", group: "country" },
  { value: "Niger", label: "Niger", group: "country" },
  { value: "Nigeria", label: "Nigeria", group: "country" },
  { value: "North Korea", label: "North Korea", group: "country" },
  { value: "North Macedonia", label: "North Macedonia", group: "country" },
  { value: "Norway", label: "Norway", group: "country" },
  { value: "Oman", label: "Oman", group: "country" },
  { value: "Pakistan", label: "Pakistan", group: "country" },
  { value: "Palau", label: "Palau", group: "country" },
  { value: "Palestine", label: "Palestine", group: "country" },
  { value: "Panama", label: "Panama", group: "country" },
  { value: "Papua New Guinea", label: "Papua New Guinea", group: "country" },
  { value: "Paraguay", label: "Paraguay", group: "country" },
  { value: "Peru", label: "Peru", group: "country" },
  { value: "Philippines", label: "Philippines", group: "country" },
  { value: "Poland", label: "Poland", group: "country" },
  { value: "Portugal", label: "Portugal", group: "country" },
  { value: "Qatar", label: "Qatar", group: "country" },
  { value: "Romania", label: "Romania", group: "country" },
  { value: "Russia", label: "Russia", group: "country" },
  { value: "Rwanda", label: "Rwanda", group: "country" },
  {
    value: "Saint Kitts and Nevis",
    label: "Saint Kitts and Nevis",
    group: "country",
  },
  { value: "Saint Lucia", label: "Saint Lucia", group: "country" },
  {
    value: "Saint Vincent and the Grenadines",
    label: "Saint Vincent and the Grenadines",
    group: "country",
  },
  { value: "Samoa", label: "Samoa", group: "country" },
  { value: "San Marino", label: "San Marino", group: "country" },
  {
    value: "Sao Tome and Principe",
    label: "Sao Tome and Principe",
    group: "country",
  },
  { value: "Saudi Arabia", label: "Saudi Arabia", group: "country" },
  { value: "Senegal", label: "Senegal", group: "country" },
  { value: "Serbia", label: "Serbia", group: "country" },
  { value: "Seychelles", label: "Seychelles", group: "country" },
  { value: "Sierra Leone", label: "Sierra Leone", group: "country" },
  { value: "Singapore", label: "Singapore", group: "country" },
  { value: "Slovakia", label: "Slovakia", group: "country" },
  { value: "Slovenia", label: "Slovenia", group: "country" },
  { value: "Solomon Islands", label: "Solomon Islands", group: "country" },
  { value: "Somalia", label: "Somalia", group: "country" },
  { value: "South Africa", label: "South Africa", group: "country" },
  { value: "South Korea", label: "South Korea", group: "country" },
  { value: "South Sudan", label: "South Sudan", group: "country" },
  { value: "Spain", label: "Spain", group: "country" },
  { value: "Sri Lanka", label: "Sri Lanka", group: "country" },
  { value: "Sudan", label: "Sudan", group: "country" },
  { value: "Suriname", label: "Suriname", group: "country" },
  { value: "Sweden", label: "Sweden", group: "country" },
  { value: "Switzerland", label: "Switzerland", group: "country" },
  { value: "Syria", label: "Syria", group: "country" },
  { value: "Taiwan", label: "Taiwan", group: "country" },
  { value: "Tajikistan", label: "Tajikistan", group: "country" },
  { value: "Tanzania", label: "Tanzania", group: "country" },
  { value: "Thailand", label: "Thailand", group: "country" },
  { value: "Togo", label: "Togo", group: "country" },
  { value: "Tonga", label: "Tonga", group: "country" },
  {
    value: "Trinidad and Tobago",
    label: "Trinidad and Tobago",
    group: "country",
  },
  { value: "Tunisia", label: "Tunisia", group: "country" },
  { value: "Turkey", label: "Turkey", group: "country" },
  { value: "Turkmenistan", label: "Turkmenistan", group: "country" },
  { value: "Tuvalu", label: "Tuvalu", group: "country" },
  { value: "Uganda", label: "Uganda", group: "country" },
  { value: "Ukraine", label: "Ukraine", group: "country" },
  {
    value: "United Arab Emirates",
    label: "United Arab Emirates",
    group: "country",
  },
  { value: "United Kingdom", label: "United Kingdom", group: "country" },
  { value: "United States", label: "United States", group: "country" },
  { value: "Uruguay", label: "Uruguay", group: "country" },
  { value: "Uzbekistan", label: "Uzbekistan", group: "country" },
  { value: "Vanuatu", label: "Vanuatu", group: "country" },
  { value: "Vatican City", label: "Vatican City", group: "country" },
  { value: "Venezuela", label: "Venezuela", group: "country" },
  { value: "Vietnam", label: "Vietnam", group: "country" },
  { value: "Yemen", label: "Yemen", group: "country" },
  { value: "Zambia", label: "Zambia", group: "country" },
  { value: "Zimbabwe", label: "Zimbabwe", group: "country" },
];

export const commonLocations: Option[] = remoteOptions
  .concat(regionOptions)
  .concat(countryOptions);

export const commonTags = [
  {
    value: "Marketing",
    label: "Marketing",
  },
  {
    value: "Education",
    label: "Education",
  },
  {
    value: "ChatGPT",
    label: "ChatGPT",
  },
  {
    value: "Claude",
    label: "Claude",
  },
  {
    value: "Gemini",
    label: "Gemini",
  },
  {
    value: "LangChain",
    label: "LangChain",
  },
  {
    value: "Research",
    label: "Research",
  },
  {
    value: "Generative AI",
    label: "Generative AI",
  },
];
