import { LocationTypeEnum } from "@/client";

export interface LocationOption {
  readonly value: string;
  readonly label: string;
  readonly type: LocationTypeEnum;
}

export const regionOptions: readonly LocationOption[] = [
  { value: "Africa", label: "Africa", type: "region" },
  { value: "Asia", label: "Asia", type: "region" },
  { value: "Europe", label: "Europe", type: "region" },
  { value: "Latin America", label: "Latin America", type: "region" },
  { value: "Middle East", label: "Middle East", type: "region" },
  { value: "North America", label: "North America", type: "region" },
  { value: "Oceania", label: "Oceania", type: "region" },
  { value: "Worldwide", label: "Worldwide", type: "region" },
];

export const countryOptions: readonly LocationOption[] = [
  { value: "Afghanistan", label: "Afghanistan", type: "country" },
  { value: "Albania", label: "Albania", type: "country" },
  { value: "Algeria", label: "Algeria", type: "country" },
  { value: "Andorra", label: "Andorra", type: "country" },
  { value: "Angola", label: "Angola", type: "country" },
  {
    value: "Antigua and Barbuda",
    label: "Antigua and Barbuda",
    type: "country",
  },
  { value: "Argentina", label: "Argentina", type: "country" },
  { value: "Armenia", label: "Armenia", type: "country" },
  { value: "Australia", label: "Australia", type: "country" },
  { value: "Austria", label: "Austria", type: "country" },
  { value: "Azerbaijan", label: "Azerbaijan", type: "country" },
  { value: "Bahamas", label: "Bahamas", type: "country" },
  { value: "Bahrain", label: "Bahrain", type: "country" },
  { value: "Bangladesh", label: "Bangladesh", type: "country" },
  { value: "Barbados", label: "Barbados", type: "country" },
  { value: "Belarus", label: "Belarus", type: "country" },
  { value: "Belgium", label: "Belgium", type: "country" },
  { value: "Belize", label: "Belize", type: "country" },
  { value: "Benin", label: "Benin", type: "country" },
  { value: "Bhutan", label: "Bhutan", type: "country" },
  { value: "Bolivia", label: "Bolivia", type: "country" },
  {
    value: "Bosnia and Herzegovina",
    label: "Bosnia and Herzegovina",
    type: "country",
  },
  { value: "Botswana", label: "Botswana", type: "country" },
  { value: "Brazil", label: "Brazil", type: "country" },
  { value: "Brunei", label: "Brunei", type: "country" },
  { value: "Bulgaria", label: "Bulgaria", type: "country" },
  { value: "Burkina Faso", label: "Burkina Faso", type: "country" },
  { value: "Burundi", label: "Burundi", type: "country" },
  { value: "Cabo Verde", label: "Cabo Verde", type: "country" },
  { value: "Cambodia", label: "Cambodia", type: "country" },
  { value: "Cameroon", label: "Cameroon", type: "country" },
  { value: "Canada", label: "Canada", type: "country" },
  {
    value: "Central African Republic",
    label: "Central African Republic",
    type: "country",
  },
  { value: "Chad", label: "Chad", type: "country" },
  { value: "Chile", label: "Chile", type: "country" },
  { value: "China", label: "China", type: "country" },
  { value: "Colombia", label: "Colombia", type: "country" },
  { value: "Comoros", label: "Comoros", type: "country" },
  { value: "Congo", label: "Congo", type: "country" },
  { value: "Costa Rica", label: "Costa Rica", type: "country" },
  { value: "Croatia", label: "Croatia", type: "country" },
  { value: "Cuba", label: "Cuba", type: "country" },
  { value: "Cyprus", label: "Cyprus", type: "country" },
  { value: "Czech Republic", label: "Czech Republic", type: "country" },
  {
    value: "Democratic Republic of the Congo",
    label: "Democratic Republic of the Congo",
    type: "country",
  },
  { value: "Denmark", label: "Denmark", type: "country" },
  { value: "Djibouti", label: "Djibouti", type: "country" },
  { value: "Dominica", label: "Dominica", type: "country" },
  { value: "Dominican Republic", label: "Dominican Republic", type: "country" },
  { value: "East Timor", label: "East Timor", type: "country" },
  { value: "Ecuador", label: "Ecuador", type: "country" },
  { value: "Egypt", label: "Egypt", type: "country" },
  { value: "El Salvador", label: "El Salvador", type: "country" },
  { value: "Equatorial Guinea", label: "Equatorial Guinea", type: "country" },
  { value: "Eritrea", label: "Eritrea", type: "country" },
  { value: "Estonia", label: "Estonia", type: "country" },
  { value: "Eswatini", label: "Eswatini", type: "country" },
  { value: "Ethiopia", label: "Ethiopia", type: "country" },
  { value: "Fiji", label: "Fiji", type: "country" },
  { value: "Finland", label: "Finland", type: "country" },
  { value: "France", label: "France", type: "country" },
  { value: "Gabon", label: "Gabon", type: "country" },
  { value: "Gambia", label: "Gambia", type: "country" },
  { value: "Georgia", label: "Georgia", type: "country" },
  { value: "Germany", label: "Germany", type: "country" },
  { value: "Ghana", label: "Ghana", type: "country" },
  { value: "Greece", label: "Greece", type: "country" },
  { value: "Grenada", label: "Grenada", type: "country" },
  { value: "Guatemala", label: "Guatemala", type: "country" },
  { value: "Guinea", label: "Guinea", type: "country" },
  { value: "Guinea-Bissau", label: "Guinea-Bissau", type: "country" },
  { value: "Guyana", label: "Guyana", type: "country" },
  { value: "Haiti", label: "Haiti", type: "country" },
  { value: "Honduras", label: "Honduras", type: "country" },
  { value: "Hungary", label: "Hungary", type: "country" },
  { value: "Iceland", label: "Iceland", type: "country" },
  { value: "India", label: "India", type: "country" },
  { value: "Indonesia", label: "Indonesia", type: "country" },
  { value: "Iran", label: "Iran", type: "country" },
  { value: "Iraq", label: "Iraq", type: "country" },
  { value: "Ireland", label: "Ireland", type: "country" },
  { value: "Israel", label: "Israel", type: "country" },
  { value: "Italy", label: "Italy", type: "country" },
  { value: "Ivory Coast", label: "Ivory Coast", type: "country" },
  { value: "Jamaica", label: "Jamaica", type: "country" },
  { value: "Japan", label: "Japan", type: "country" },
  { value: "Jordan", label: "Jordan", type: "country" },
  { value: "Kazakhstan", label: "Kazakhstan", type: "country" },
  { value: "Kenya", label: "Kenya", type: "country" },
  { value: "Kiribati", label: "Kiribati", type: "country" },
  { value: "Kosovo", label: "Kosovo", type: "country" },
  { value: "Kuwait", label: "Kuwait", type: "country" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan", type: "country" },
  { value: "Laos", label: "Laos", type: "country" },
  { value: "Latvia", label: "Latvia", type: "country" },
  { value: "Lebanon", label: "Lebanon", type: "country" },
  { value: "Lesotho", label: "Lesotho", type: "country" },
  { value: "Liberia", label: "Liberia", type: "country" },
  { value: "Libya", label: "Libya", type: "country" },
  { value: "Liechtenstein", label: "Liechtenstein", type: "country" },
  { value: "Lithuania", label: "Lithuania", type: "country" },
  { value: "Luxembourg", label: "Luxembourg", type: "country" },
  { value: "Madagascar", label: "Madagascar", type: "country" },
  { value: "Malawi", label: "Malawi", type: "country" },
  { value: "Malaysia", label: "Malaysia", type: "country" },
  { value: "Maldives", label: "Maldives", type: "country" },
  { value: "Mali", label: "Mali", type: "country" },
  { value: "Malta", label: "Malta", type: "country" },
  { value: "Marshall Islands", label: "Marshall Islands", type: "country" },
  { value: "Mauritania", label: "Mauritania", type: "country" },
  { value: "Mauritius", label: "Mauritius", type: "country" },
  { value: "Mexico", label: "Mexico", type: "country" },
  { value: "Micronesia", label: "Micronesia", type: "country" },
  { value: "Moldova", label: "Moldova", type: "country" },
  { value: "Monaco", label: "Monaco", type: "country" },
  { value: "Mongolia", label: "Mongolia", type: "country" },
  { value: "Montenegro", label: "Montenegro", type: "country" },
  { value: "Morocco", label: "Morocco", type: "country" },
  { value: "Mozambique", label: "Mozambique", type: "country" },
  { value: "Myanmar", label: "Myanmar", type: "country" },
  { value: "Namibia", label: "Namibia", type: "country" },
  { value: "Nauru", label: "Nauru", type: "country" },
  { value: "Nepal", label: "Nepal", type: "country" },
  { value: "Netherlands", label: "Netherlands", type: "country" },
  { value: "New Zealand", label: "New Zealand", type: "country" },
  { value: "Nicaragua", label: "Nicaragua", type: "country" },
  { value: "Niger", label: "Niger", type: "country" },
  { value: "Nigeria", label: "Nigeria", type: "country" },
  { value: "North Korea", label: "North Korea", type: "country" },
  { value: "North Macedonia", label: "North Macedonia", type: "country" },
  { value: "Norway", label: "Norway", type: "country" },
  { value: "Oman", label: "Oman", type: "country" },
  { value: "Pakistan", label: "Pakistan", type: "country" },
  { value: "Palau", label: "Palau", type: "country" },
  { value: "Palestine", label: "Palestine", type: "country" },
  { value: "Panama", label: "Panama", type: "country" },
  { value: "Papua New Guinea", label: "Papua New Guinea", type: "country" },
  { value: "Paraguay", label: "Paraguay", type: "country" },
  { value: "Peru", label: "Peru", type: "country" },
  { value: "Philippines", label: "Philippines", type: "country" },
  { value: "Poland", label: "Poland", type: "country" },
  { value: "Portugal", label: "Portugal", type: "country" },
  { value: "Qatar", label: "Qatar", type: "country" },
  { value: "Romania", label: "Romania", type: "country" },
  { value: "Russia", label: "Russia", type: "country" },
  { value: "Rwanda", label: "Rwanda", type: "country" },
  {
    value: "Saint Kitts and Nevis",
    label: "Saint Kitts and Nevis",
    type: "country",
  },
  { value: "Saint Lucia", label: "Saint Lucia", type: "country" },
  {
    value: "Saint Vincent and the Grenadines",
    label: "Saint Vincent and the Grenadines",
    type: "country",
  },
  { value: "Samoa", label: "Samoa", type: "country" },
  { value: "San Marino", label: "San Marino", type: "country" },
  {
    value: "Sao Tome and Principe",
    label: "Sao Tome and Principe",
    type: "country",
  },
  { value: "Saudi Arabia", label: "Saudi Arabia", type: "country" },
  { value: "Senegal", label: "Senegal", type: "country" },
  { value: "Serbia", label: "Serbia", type: "country" },
  { value: "Seychelles", label: "Seychelles", type: "country" },
  { value: "Sierra Leone", label: "Sierra Leone", type: "country" },
  { value: "Singapore", label: "Singapore", type: "country" },
  { value: "Slovakia", label: "Slovakia", type: "country" },
  { value: "Slovenia", label: "Slovenia", type: "country" },
  { value: "Solomon Islands", label: "Solomon Islands", type: "country" },
  { value: "Somalia", label: "Somalia", type: "country" },
  { value: "South Africa", label: "South Africa", type: "country" },
  { value: "South Korea", label: "South Korea", type: "country" },
  { value: "South Sudan", label: "South Sudan", type: "country" },
  { value: "Spain", label: "Spain", type: "country" },
  { value: "Sri Lanka", label: "Sri Lanka", type: "country" },
  { value: "Sudan", label: "Sudan", type: "country" },
  { value: "Suriname", label: "Suriname", type: "country" },
  { value: "Sweden", label: "Sweden", type: "country" },
  { value: "Switzerland", label: "Switzerland", type: "country" },
  { value: "Syria", label: "Syria", type: "country" },
  { value: "Taiwan", label: "Taiwan", type: "country" },
  { value: "Tajikistan", label: "Tajikistan", type: "country" },
  { value: "Tanzania", label: "Tanzania", type: "country" },
  { value: "Thailand", label: "Thailand", type: "country" },
  { value: "Togo", label: "Togo", type: "country" },
  { value: "Tonga", label: "Tonga", type: "country" },
  {
    value: "Trinidad and Tobago",
    label: "Trinidad and Tobago",
    type: "country",
  },
  { value: "Tunisia", label: "Tunisia", type: "country" },
  { value: "Turkey", label: "Turkey", type: "country" },
  { value: "Turkmenistan", label: "Turkmenistan", type: "country" },
  { value: "Tuvalu", label: "Tuvalu", type: "country" },
  { value: "Uganda", label: "Uganda", type: "country" },
  { value: "Ukraine", label: "Ukraine", type: "country" },
  {
    value: "United Arab Emirates",
    label: "United Arab Emirates",
    type: "country",
  },
  { value: "United Kingdom", label: "United Kingdom", type: "country" },
  { value: "United States", label: "United States", type: "country" },
  { value: "Uruguay", label: "Uruguay", type: "country" },
  { value: "Uzbekistan", label: "Uzbekistan", type: "country" },
  { value: "Vanuatu", label: "Vanuatu", type: "country" },
  { value: "Vatican City", label: "Vatican City", type: "country" },
  { value: "Venezuela", label: "Venezuela", type: "country" },
  { value: "Vietnam", label: "Vietnam", type: "country" },
  { value: "Yemen", label: "Yemen", type: "country" },
  { value: "Zambia", label: "Zambia", type: "country" },
  { value: "Zimbabwe", label: "Zimbabwe", type: "country" },
];

export interface GroupedOption {
  readonly label: string;
  readonly options: readonly LocationOption[];
}

export const groupedOptions: readonly GroupedOption[] = [
  {
    label: "Regions",
    options: regionOptions,
  },
  {
    label: "Countries",
    options: countryOptions,
  },
];

// export interface CategoryOption {
//   readonly id: string;
//   readonly text: string;
//   readonly slug: LocationTypeEnum;
// }

// export interface CategoryOption {
//   readonly options: readonly LocationOption[];
// }

export const commonTags = [
  {
    value: "Marketing",
    label: "Marketing",
  },
  {
    value: "Education",
    label: "Education",
  },
  {
    value: "Chat GPT",
    label: "Chat GPT",
  },
  {
    value: "Claude",
    label: "Claude",
  },
  {
    value: "Gemini",
    label: "Gemini",
  },
  {
    value: "LangChain",
    label: "LangChain",
  },
  {
    value: "Research",
    label: "Research",
  },
  {
    value: "Generative AI",
    label: "Generative AI",
  },
];
