# Generated by Django 5.0.6 on 2024-09-03 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='Product id')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product name')),
                ('variant_id', models.IntegerField(unique=True, verbose_name='Variant id')),
                ('category', models.CharField(max_length=30, verbose_name='Category')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Variant description')),
                ('price', models.CharField(max_length=30, verbose_name='Price')),
                ('is_usage_based', models.BooleanField(default=False, verbose_name='Is usage based')),
                ('interval', models.CharField(max_length=10, verbose_name='Interval')),
                ('interval_count', models.IntegerField(verbose_name='Interval count')),
                ('trial_interval', models.CharField(max_length=10, null=True, verbose_name='Trial interval')),
                ('trial_interval_count', models.IntegerField(null=True, verbose_name='Trial interval count')),
                ('sort', models.IntegerField(verbose_name='Sort')),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemonsqueezy_id', models.CharField(max_length=255, unique=True, verbose_name='Lemon Squeezy Id')),
                ('order_id', models.IntegerField(verbose_name='Order Id')),
                ('order_number', models.IntegerField(verbose_name='Order Number')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('status_formatted', models.CharField(max_length=100, verbose_name='Status Formatted')),
                ('refunded', models.BooleanField(default=False, verbose_name='Refunded')),
                ('refunded_at', models.CharField(max_length=100, verbose_name='Refunded At')),
                ('price', models.CharField(blank=True, max_length=30, verbose_name='Price')),
                ('receipt', models.CharField(max_length=500, null=True)),
                ('order_item_id', models.BigIntegerField(null=True, verbose_name='Order Item Id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.plan')),
            ],
            options={
                'ordering': ['-lemonsqueezy_id'],
                'indexes': [models.Index(fields=['user'], name='billing_ord_user_id_537c1b_idx'), models.Index(fields=['plan'], name='billing_ord_plan_id_0c9a12_idx'), models.Index(fields=['lemonsqueezy_id'], name='billing_ord_lemonsq_8f8378_idx')],
            },
        ),
    ]
