# Generated by Django 5.0.6 on 2025-10-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('news', 'News'), ('training', 'Training'), ('promo', 'Promo'), ('other', 'Other')], db_index=True, max_length=20, verbose_name='Post Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('body', models.TextField(verbose_name='Body (Text Format)')),
                ('body_md', models.TextField(verbose_name='Body (Markdown Format)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
            ],
            options={
                'db_table': 'newsletter_posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
