# Generated by Django 5.0.6 on 2025-10-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_url',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='External URL'),
        ),
    ]
