# Generated by Django 5.0.6 on 2025-10-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_post_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Image URL'),
        ),
    ]
