# Generated by Django 5.0.6 on 2025-10-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_post_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='Metadata'),
        ),
    ]
