# Generated by Django 5.0.6 on 2024-12-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='categories',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dribbble_link',
            field=models.URLField(blank=True, null=True, verbose_name='Dribbble profile'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='github_link',
            field=models.URLField(blank=True, null=True, verbose_name='Github profile'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn profile'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True, verbose_name='Portfolio'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='projects',
            field=models.JSONField(blank=True, null=True, verbose_name='Projects'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='skills',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='work_experience',
            field=models.JSONField(blank=True, null=True, verbose_name='Work Experience'),
        ),
    ]
